version: '3.8'
include:
  - ./proxy.yaml
services:
  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST="%"
    networks:
      backend:
        ipv4_address: 172.20.0.10
    ports:
      - 5000:5000
    restart: on-failure

  web:
    build:
      dockerfile: ./Dockerfile.python
    depends_on:
      - db
    networks:
      backend:
        ipv4_address: 172.20.0.5
    ports:
      - 3306:3306
    environment:
      - DB_HOST=db
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
    restart: on-failure